// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catan;

/************************************************************/
/**
 * 
 */
public class Action {
	/**
	 * 
	 * @return 
	 */
	public Node[] getNode() {
	}

	/**
	 * 
	 * @return 
	 */
	public Building getPiece() {
	}
}
