// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catan;

/************************************************************/
/**
 * 
 */
public class AgentPlayer extends Player {
	/**
	 * 
	 */
	public DecisionStrategy decisionstrategy;

	/**
	 * 
	 * @param strategy 
	 */
	public void setDecisionStrategy(DecisionStrategy strategy) {
	}
}
