// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catan;

import catansim.Catalog;
import catansim.PlayerID;
import catansim.Resource;

/************************************************************/
/**
 * 
 */
public interface Board extends StaticBoard {
	/**
	 * 
	 */
	private Node[] nodes;
	/**
	 * 
	 */
	private Tile[] tiles;

	/**
	 * 
	 * @param nodes 
	 */
	public void createNodes(Node[] nodes);

	/**
	 * 
	 * @return 
	 */
	public Node[] createNodes();

	/**
	 * 
	 */
	public void createTiles();

	/**
	 * 
	 * @param playerID 
	 * @return 
	 */
	public Catalog<Resource> collect(int diceNum, PlayerID playerID);
}
