// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catan;

/************************************************************/
/**
 * 
 */
public interface Board extends StaticBoard {
	/**
	 * 
	 */
	public Node[] node;
	/**
	 * 
	 */
	public Tile[] tile;

	/**
	 * 
	 * @param nodes 
	 */
	public void createNodes(Node[] nodes);

	/**
	 * 
	 * @return 
	 */
	public Node[] createNodes();

	/**
	 * 
	 */
	public void createTiles();

	/**
	 * 
	 * @param playerID 
	 * @return 
	 */
	public Catalog collect(PlayerIDs playerID);
}
