// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catan;

/************************************************************/
/**
 * 
 */
public class Board implements StaticBoard {
	/**
	 * 
	 */
	public Node[] node;
	/**
	 * 
	 */
	public Tile[] tile;

	/**
	 * 
	 */
	public void check() {
	}
}
