// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catan;

/************************************************************/
/**
 * 
 */
public class BuildAction extends Action {
	/**
	 * 
	 * @return 
	 */
	public Node getNodes() {
	}

	/**
	 * 
	 * @return 
	 */
	public PieceTypes getPieceType() {
	}
}
