// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catan;

/************************************************************/
/**
 * 
 */
public class Caretaker {
	/**
	 * 
	 */
	public undef gamememento;
	/**
	 * 
	 */
	public GameSnapshot class1;

	/**
	 * 
	 * @param snapshot 
	 */
	public void save(GameSnapshot snapshot) {
	}

	/**
	 * 
	 * @return 
	 */
	public GameSnapshot popUndo() {
	}

	/**
	 * 
	 * @return 
	 */
	public GameSnapshot popRedo() {
	}

	/**
	 * 
	 * @param snapshot 
	 */
	public void pushUndo(GameSnapshot snapshot) {
	}

	/**
	 * 
	 * @param snapshot 
	 */
	public void pushRedo(GameSnapshot snapshot) {
	}

	/**
	 * 
	 */
	public void clear() {
	}
}
