// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catan;

/************************************************************/
/**
 * 
 */
public interface DecisionStrategy {
	/**
	 * 
	 * @param actions 
	 * @param board 
	 * @return 
	 */
	public Action decideAction(Action[] actions, StaticBoard board);
}
