// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catan;

/************************************************************/
/**
 * 
 */
public class Game {
	/**
	 * 
	 */
	public Validator validator;
	/**
	 * 
	 */
	public Dice dice;
	/**
	 * 
	 */
	public StateMachine state;
	/**
	 * 
	 */
	public Parser parser;
	/**
	 * 
	 */
	public Caretaker gamecaretaker;
	/**
	 * 
	 */
	public Board board;
	/**
	 * 
	 */
	public Player player;

	/**
	 * 
	 */
	private void doNextRound() {
	}

	/**
	 * 
	 */
	public void start() {
	}

	/**
	 * 
	 * @param visualizer 
	 */
	public void addVisualizer(Visualizer visualizer) {
	}

	/**
	 * 
	 */
	private void notifyVisualizers() {
	}

	/**
	 * 
	 */
	private void undo() {
	}

	/**
	 * 
	 */
	private void redo() {
	}
}
