// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catan;

/************************************************************/
/**
 * 
 */
public class GamePythonVisualizer implements Visualizer {
	/**
	 * 
	 */
	public Game game;
	/**
	 * 
	 */
	public StaticBoard staticboard;

	/**
	 * 
	 */
	private void render() {
	}
}
