// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catan;

/************************************************************/
/**
 * 
 */
public class Game {
	/**
	 * 
	 */
	public Board board;
	/**
	 * 
	 */
	public Validator validator;
	/**
	 * 
	 */
	public Player[] player;
	/**
	 * 
	 */
	public Dice dice;

	/**
	 * 
	 */
	private void doNextRound() {
	}

	/**
	 * 
	 */
	public void start() {
	}
}
