// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catan;

/************************************************************/
/**
 * 
 */
public class GameCaretaker implements Caretaker {
	/**
	 * 
	 */
	public GameMemento gamememento;
	/**
	 * 
	 */
	public GameOriginator gameoriginator;
}
