// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catan;

/************************************************************/
/**
 * 
 */
public class GameOriginator {
	/**
	 * 
	 */
	public Board board;
	/**
	 * 
	 */
	public Player[] player;

	/**
	 * 
	 * @param memento 
	 */
	public void restore(GameMemento memento) {
	}

	/**
	 * 
	 * @return 
	 */
	public GameMemento Operation1() {
	}
}
