// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catan;

/************************************************************/
/**
 * 
 */
public class HardWiredBoard implements Board {
	/**
	 * 
	 */
	private void createBoardHardWired() {
	}
}
