// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catan;

/************************************************************/
/**
 * 
 */
public class Invoker {
	/**
	 * 
	 */
	public CommandManager commandmanager;

	/**
	 * 
	 */
	public void execute() {
	}
}
