// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catan;

/************************************************************/
/**
 * 
 */
public class Node {
	/**
	 * 
	 */
	public Tile[] tiles;
	/**
	 * 
	 */
	private int nodeID;
	/**
	 * 
	 */
	private Node[] neighbours;
	/**
	 * 
	 */
	private Road[] roads;
	/**
	 * 
	 */
	private Building building;

	/**
	 * 
	 * @param diceNum 
	 * @return 
	 */
	public boolean checkTiles(int diceNum) {
	}

	/**
	 * 
	 * @param node 
	 */
	public void connectNode(Node node) {
	}
}
