// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catan;

/************************************************************/
/**
 * 
 */
public class Node {
	/**
	 * 
	 */
	public Tile[] tiles;
	/**
	 * 
	 */
	private int nodeID;
	/**
	 * 
	 */
	private Node[] neighbours;
	/**
	 * 
	 */
	private Road road;
	/**
	 * 
	 */
	private Building building;
}
