// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catan;

/************************************************************/
/**
 * 
 */
public interface Originator {
	/**
	 * 
	 * @return 
	 */
	public Memento createMemento();

	/**
	 * 
	 * @param memento 
	 */
	public void restore(Memento memento);
}
