// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catan;

/************************************************************/
/**
 * 
 */
public class Parser {
	/**
	 * 
	 * @param a 
	 */
	public static void parse(Action a) {
	}
}
