// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catan;

/************************************************************/
/**
 * 
 */
public class PieceHandler {
	/**
	 * 
	 */
	public Catalog catalog;

	/**
	 * 
	 * @param buildingType 
	 * @return 
	 */
	public Piece sendPieceOfType(PieceTypes buildingType) {
	}

	/**
	 * 
	 * @param piece 
	 */
	public void usePiece(PieceTypes piece) {
	}

	/**
	 * 
	 * @param piece 
	 */
	public void refundPiece(Piece piece) {
	}

	/**
	 * 
	 * @param Piece 
	 */
	public void refundPiece(PieceTypes Piece) {
	}
}
