// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catan;

/************************************************************/
/**
 * 
 */
public interface Piece {
	/**
	 * 
	 */
	public PlayerIDs ownerPlayerID;
	/**
	 * 
	 */
	public ResourceCatalog resourcecatalog;
}
