// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catan;

/************************************************************/
/**
 * 
 */
public enum PieceTypes {
	/**
	 * 
	 */
	ROAD,
	/**
	 * 
	 */
	SETTLEMENT,
	/**
	 * 
	 */
	CITY;

	/**
	 * 
	 */
	public Catalog catalog;
}
