// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catan;

/************************************************************/
/**
 * 
 */
public class PieceHandler {
	/**
	 * 
	 */
	public void sendPieceOfType() {
	}

	/**
	 * 
	 * @param piece 
	 */
	public void usePiece(Piece piece) {
	}
}
