// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catan;

/************************************************************/
/**
 * 
 */
public class Player {
	/**
	 * 
	 */
	public interface Interface1 {
	};

	/**
	 * 
	 */
	public interface Interface2 {
	};

	/**
	 * 
	 */
	private PlayerID PlayerID;
	/**
	 * 
	 */
	public PlayerHand hand;
	/**
	 * 
	 */
	public PieceHandler piecehandler;
	/**
	 * 
	 */
	public PlayerID playerid;

	/**
	 * 
	 * @param Parameter1 
	 * @return 
	 */
	public Action choose(Action[] Parameter1) {
	}

	/**
	 * 
	 * @param catalog 
	 * @return 
	 */
	public boolean dealResources(Catalog catalog) {
	}

	/**
	 * 
	 * @return 
	 * @param buildingType 
	 */
	public Piece getPieceOfType(PieceTypes buildingType) {
	}

	/**
	 * 
	 * @param buildingType 
	 */
	public void consumePiece(PieceTypes buildingType) {
	}

	/**
	 * 
	 * @param buildingType 
	 */
	public void consumeFreePiece(PieceTypes buildingType) {
	}
}
