// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catan;

/************************************************************/
/**
 * 
 */
public class PlayerHand {
	/**
	 * 
	 */
	public Resource resource;
	/**
	 * 
	 */
	public Catalog catalog;

	/**
	 * 
	 * @param resource 
	 * @param count 
	 * @return 
	 */
	public boolean addCard(Resource resource, int count) {
	}

	/**
	 * 
	 * @param resource 
	 * @param count 
	 * @return 
	 */
	public boolean removeCard(Resource resource, int count) {
	}

	/**
	 * 
	 * @param catalog 
	 * @return 
	 */
	public boolean addHand(Catalog catalog) {
	}

	/**
	 * 
	 * @param catalog 
	 * @return 
	 */
	public boolean removeHand(Catalog catalog) {
	}

	/**
	 * 
	 * @param unit 
	 * @return 
	 */
	public int getCount(Resource unit) {
	}

	/**
	 * 
	 * @return 
	 */
	public Catalog snapshot() {
	}
}
