// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catan;

/************************************************************/
/**
 * 
 */
public interface PlayerHand extends ResourceCatalog {
	/**
	 * 
	 * @param resource 
	 * @param count 
	 * @return 
	 */
	public boolean addCard(Resource resource, int count);

	/**
	 * 
	 * @param resource 
	 * @param count 
	 * @return 
	 */
	public boolean removeCard(Resource resource, int count);

	/**
	 * 
	 * @param catalog 
	 * @return 
	 */
	public boolean removeHand(ResourceCatalog catalog);

	/**
	 * 
	 * @param catalog 
	 * @return 
	 */
	public boolean addHand(ResourceCatalog catalog);
}
