// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catan;

/************************************************************/
/**
 * 
 */
public abstract class Player {
	/**
	 * 
	 */
	public interface Interface1 {
	};

	/**
	 * 
	 */
	public interface Interface2 {
	};

	/**
	 * 
	 */
	private PlayerID PlayerID;
	/**
	 * 
	 */
	public PieceHandler piecehandler;
	/**
	 * 
	 */
	public PlayerID playerid;
	/**
	 * 
	 */
	public PlayerHand playerhand;
	/**
	 * 
	 */
	public Parser parser;

	/**
	 * 
	 * @param actions 
	 * @return 
	 * @param board 
	 */
	public Action choose(Action[] actions, StaticBoard board) {
	}

	/**
	 * 
	 * @param catalog 
	 * @return 
	 */
	public boolean dealResources(Catalog catalog) {
	}

	/**
	 * 
	 * @return 
	 * @param buildingType 
	 */
	public Piece getPieceOfType(PieceTypes buildingType) {
	}

	/**
	 * 
	 * @param buildingType 
	 */
	public void consumePiece(PieceTypes buildingType) {
	}

	/**
	 * 
	 * @param buildingType 
	 */
	public void consumeFreePiece(PieceTypes buildingType) {
	}
}
