// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catan;

/************************************************************/
/**
 * 
 */
public interface ResourceCatalog {
	/**
	 * 
	 * @param resource 
	 * @return 
	 */
	public int getResourceCount(Resource resource);
}
