// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catan;

/************************************************************/
/**
 * 
 */
public interface StaticBoard {
	/**
	 * 
	 */
	public class board {
	};

	/**
	 * 
	 * @return 
	 */
	public PlayerID checkLongestRoad();

	/**
	 * 
	 * @param piece 
	 * @param nodeToPlaceOn 
	 * @return 
	 */
	public boolean canPlace(Piece piece, Node nodeToPlaceOn);

	/**
	 * 
	 * @param piece 
	 * @param nodeStart 
	 * @param nodeEnd 
	 * @return 
	 */
	public boolean canPlace(Piece piece, Node nodeStart, Node nodeEnd);
}
