// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catan;

/************************************************************/
/**
 * 
 */
public class State {
	/**
	 * 
	 */
	public GameStates gamestates;

	/**
	 * 
	 * @param state 
	 */
	public void getCurrentState(GameStates state) {
	}

	/**
	 * 
	 * @param a 
	 */
	public void read(Action a) {
	}
}
