// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catan;

/************************************************************/
/**
 * 
 */
public interface StaticBoard {
	/**
	 * 
	 */
	public class board {
	};

	/**
	 * 
	 * @return 
	 */
	public PlayerID checkLongestRoad();

	/**
	 * 
	 * @param piece 
	 * @param nodeToPlaceOn 
	 * @return 
	 */
	public boolean canPlace(Piece piece, Node nodeToPlaceOn);

	/**
	 * 
	 * @param piece 
	 * @param nodeStart 
	 * @param nodeEnd 
	 * @return 
	 */
	public boolean canPlace(Piece piece, Node nodeStart, Node nodeEnd);

	/**
	 * 
	 * @return 
	 */
	public Tile getRobberTile();

	/**
	 * 
	 * @return 
	 */
	public int getLongestRoadLength();

	/**
	 * 
	 * @param action 
	 * @param playerID 
	 */
	public void canConnectRoads(Action action, PlayerID playerID);

	/**
	 * 
	 * @param playerID 
	 * @return 
	 */
	public int getLongestRoadLength(PlayerID playerID);
}
