// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catan;

/************************************************************/
/**
 * 
 */
public class Validator {
	/**
	 * 
	 */
	public class Class1 {
	};

	/**
	 * 
	 */
	public Action[] action;

	/**
	 * 
	 * @param board 
	 * @param playerID 
	 * @param resourcesOwned 
	 * @return 
	 * @param piecesOwned 
	 * @param state 
	 */
	public Action[] getValidActions(StaticBoard board, PlayerID playerID, Catalog resourcesOwned, Catalog piecesOwned,
			GameStates state) {
	}

	/**
	 * 
	 * @param node 
	 * @return 
	 */
	public Action[] getAllActionsFromNode(Node node) {
	}

	/**
	 * 
	 * @param a 
	 * @param listOfActions 
	 * @return 
	 */
	public boolean isValid(Action a, Action[] listOfActions) {
	}
}
