// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catan;

/************************************************************/
/**
 * 
 */
public interface Visualizer {
	/**
	 * 
	 */
	public void onStateChanged();
}
