// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catansim;

/************************************************************/
/**
 * 
 */
public abstract class Board implements StaticBoard {
	/**
	 * 
	 */
	private Node[] nodes;
	/**
	 * 
	 */
	private Tile[] tiles;

	/**
	 * 
	 * @return 
	 */
	public Node[] getNodes() {
		return nodes;
	}

	/**
	 * 
	 * @param playerID 
	 * @return 
	 */
	public abstract Catalog collect(int diceNum, PlayerID playerID);
}
