// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catansim;

/************************************************************/
/**
 * 
 */
public abstract class Board implements StaticBoard {
	/**
	 * 
	 */
	private Node[] nodes;
	/**
	 * 
	 */
	private Tile[] tiles;
	
	
	/**
	 * 
	 * @return 
	 */
	public Node[] getNodes() {
		return nodes;
	}

	
	/**
	 * @param road The road piece being placed.
	 * @param playerID The player who owns the road.
	 * @param nodeOne One endpoint node of the road.
	 * @param nodeTwo The other endpoint node of the road.
	 */
	public abstract void placePiece(Road road, PlayerID playerID, Node nodeOne, Node nodeTwo);
	
	/**
	 *
	 * @param building The building piece being placed.
	 * @param playerID The player who owns the building.
	 * @param node The node where the building is placed.
	 */
	public abstract void placePiece(Building building, PlayerID playerID, Node node);

	/**
	 * 
	 * @param playerID 
	 * @return 
	 */
	public abstract Catalog collect(int diceNum, PlayerID playerID);

}
