// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catansim;

/************************************************************/
/**
 * 
 */
public abstract class Building implements Piece {
	/**
	 * 
	 */
	private int resourceAmount;
}
