// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catansim;

/************************************************************/
/**
 * 
 */
public class MapPlayerHand implements PlayerHand {
}
