// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catansim;

/************************************************************/
/**
 * 
 */
public class MultiDice implements Dice {
	/**
	 * 
	 * @param Dice 
	 */
	public void addDice(Dice Dice) {
	}
}
