// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catansim;

/************************************************************/
/**
 * 
 */
public interface Piece {
	/**
	 * 
	 */
	public PlayerID ownerPlayerID;
	/**
	 * 
	 */
	public Catalog catalog;

	/**
	 * 
	 * @param playerID 
	 */
	public void getOwnerPlayerID(PlayerID playerID);
}
