// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catansim;

/************************************************************/
/**
 * 
 */
public interface PlayerHand extends Catalog {
	/**
	 * 
	 * @param resource 
	 * @param count 
	 * @return 
	 */
	public boolean addCard(Resource resource, int count);

	/**
	 * 
	 * @param resource 
	 * @param count 
	 * @return 
	 */
	public boolean removeCard(Resource resource, int count);

	/**
	 * 
	 * @param catalog 
	 * @return 
	 */
	public boolean removeHand(Catalog catalog);

	/**
	 * 
	 * @param catalog 
	 * @return 
	 */
	public boolean addHand(Catalog catalog);
}
