// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catansim;

import java.util.Random;


/************************************************************/
/**
 * 
 */
public class Player {
	
	
	private final PlayerID playerID;
    private final PieceHandler pieceHandler;
    private final PlayerHand playerHand;

    private final Random rng = new Random();
    
    private int vp = 0;


    
    public Player(PlayerID playerID) {
        if (playerID == null) throw new IllegalArgumentException("playerID cannot be null");
        this.playerID = playerID;
        this.pieceHandler = new PieceHandler(playerID);
        this.playerHand = new MapPlayerHand();
    }
    
    
    //Getters
    public PlayerID getPlayerID() {
        return playerID;
    }
    
    
    
    //PICKING RANDOM ACTION from list of actions
    public Action chooseAction(Action[] actions) {
        if (actions == null || actions.length == 0) return null;
        return actions[rng.nextInt(actions.length)];
    }
    
    
    //DEAL RESOURCE
    public void dealResources(Catalog<Resource> gained) {
        if (gained == null) throw new IllegalArgumentException("gained cannot be null");
        playerHand.addHand(gained);
    }
    
    
    //CONSUME PIECE
    //Handles the logic to determine what to take and refund from pieceHandler.
    //If it's a city, refund a settlement since it's an upgrade.
    public Piece consumePiece(BuildingTypes type) {
        if (type == null) throw new IllegalArgumentException("type cannot be null");

        Piece toPlace = pieceHandler.usePiece(type);
        if (toPlace == null) return null;
        
        //Remove resources
        boolean paid = playerHand.removeHand(type.getCost());
        if (!paid) {
            pieceHandler.refundPiece(type);
            return null;
        }

        //City placement implies settlement upgrade
        if (type == BuildingTypes.CITY) {
            pieceHandler.refundPiece(BuildingTypes.SETTLEMENT);
        }

        return toPlace;
    }
    
    //For setup
    public Piece consumeFreePiece(BuildingTypes type) {
        if (type == null) throw new IllegalArgumentException("type cannot be null");
        return pieceHandler.usePiece(type);
    }
    
    //Get read-only catalog of pieces
    public Catalog<BuildingTypes> getPieceCatalog() {

        Catalog<BuildingTypes> catalog = new MapCatalog<BuildingTypes>();

        for (BuildingTypes type : BuildingTypes.values()) {
            catalog.add(type, pieceHandler.getAvailable(type));
        }

        return catalog.snapshot();
    }
    
    //Get read-only catalog of resources
    public Catalog<Resource> getResourceCatalog() {
        return playerHand.snapshot();
    }
    
    
    
    //Getters and mutators for VP
    public int getVP() {
        return vp;
    }

    public void addVP(int amount) {
        if (amount < 0) throw new IllegalArgumentException("amount cannot be negative");
        vp += amount;
    }

    public void removeVP(int amount) {
        if (amount < 0) throw new IllegalArgumentException("amount cannot be negative");
        if (amount > vp) throw new IllegalArgumentException("cannot remove more VP than player has");
        vp -= amount;
    }
    

    
    
}
