// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catansim;

/************************************************************/
/**
 * 
 */
public class Tile {
	
	/**
	 * 
	 */
	private Resource resource;
	/**
	 * 
	 */
	private int diceNum;
	
	
	public Tile(Resource resource, int diceNum) {
		this.resource = resource;
	}
	
	public int getDiceNum() {
		return diceNum;
	}
	
	public Resource getResource() {
		return resource;
	}
}
