// --------------------------------------------------------
// Code generated by GENAI
// --------------------------------------------------------

package catanllm;

/************************************************************/
/**
 * 
 */
public class Action {
	 public Node getNode() {
	        return null;
	    }

	    public Building getPiece() {
	        return null;
	    }
}