// --------------------------------------------------------
// Code generated by GENAI
// --------------------------------------------------------

package catanllm;

/************************************************************/
/**
 * 
 */
public interface Board {
    Node createNodes();
    Tile createTiles();
    Catalog collect(PlayerID playerID);
}