// --------------------------------------------------------
// Code generated by GENAI
// --------------------------------------------------------

package catanllm;

/************************************************************/
/**
 * 
 */
public abstract class Building implements Piece {
    protected final PlayerID owner;
    protected int resourceAmount;

    protected Building(PlayerID owner) {
        this.owner = owner;
    }

    @Override
    public PlayerID ownerPlayerID() {
        return owner;
    }

    @Override
    public Player getOwnerPlayer(PlayerID id) {
        return null;
    }
}
