// --------------------------------------------------------
// Code generated by GENAI
// --------------------------------------------------------

package catanllm;

/************************************************************/
/**
 * 
 */
public interface Catalog<T> {
	
	int getCount(Resource resource);
}
