// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catanllm;

/************************************************************/
/**
 * 
 */
public interface Catalog<T> {
	/**
	 * 
	 * @param unit 
	 * @return 
	 */
	public int getCount(T unit);
}
