// --------------------------------------------------------
// Code generated by GENAI
// --------------------------------------------------------

package catanllm;

/************************************************************/
/**
 * 
 */
public class City extends Building {
    public City(PlayerID owner) {
        super(owner);
    }
}