// --------------------------------------------------------
// Code generated by GENAI
// --------------------------------------------------------

package catanllm;

/************************************************************/
/**
 * 
 */
public class Game {
	 private final Board board;
	    private final Player[] players;
	    private final Dice dice;

	    public Game(Board board, Player[] players, Dice dice) {
	        this.board = board;
	        this.players = players;
	        this.dice = dice;
	    }

	    public void start() {
	        doNextRound();
	    }

	    public void doNextRound() {
	        for (Player player : players) {
	            int roll = dice.roll();
	        }
	    }
}