// --------------------------------------------------------
// Code generated by GENAI
// --------------------------------------------------------

package catanllm;

/************************************************************/
/**
 * 
 */
public class HardWiredBoard implements Board {
	
	@Override
    public Node createNodes() {
        return new Node(0);
    }

    @Override
    public Tile createTiles() {
        return new Tile(0, Resource.Wood, 5);
    }

    @Override
    public Catalog collect(PlayerID playerID) {
        return new MapCatalog();
    }

    @Override
    public boolean checkLongestRoad() {
        return false;
    }

    @Override
    public boolean canPlace(Piece piece, Node node) {
        return true;
    }
}