// --------------------------------------------------------
// Code generated by GENAI
// --------------------------------------------------------

package catanllm;

/************************************************************/
/**
 * 
 */
import java.util.EnumMap;

public class MapCatalog implements Catalog {
	private final EnumMap<Resource, Integer> resources = new EnumMap<>(Resource.class);

    @Override
    public int getCount(Resource resource) {
        return resources.getOrDefault(resource, 0);
    }
}