// --------------------------------------------------------
// Code generated by GENAI
// --------------------------------------------------------

package catanllm;

/************************************************************/
/**
 * 
 */
public class MapPlayerHand implements PlayerHand {
	@Override
    public void addCard(Resource resource, int count) {}

    @Override
    public int count(Resource resource) {
        return 0;
    }

    @Override
    public boolean removeHand(Catalog catalog) {
        return true;
    }

    @Override
    public boolean holdHand(Catalog catalog) {
        return false;
    }
}
