// --------------------------------------------------------
// Code generated by GENAI
// --------------------------------------------------------

package catanllm;

/************************************************************/
/**
 * 
 */
import java.util.ArrayList;
import java.util.List;

public class MultiDice implements Dice {
	private final List<Dice> dice = new ArrayList<>();
	/**
	 * 
	 * @param Dice 
	 */
	public void addDice(Dice Dice) {
		this.dice.add(dice);
	}
	
	@Override
    public int roll() {
        int sum = 0;
        for (Dice d : dice) {
            sum += d.roll();
        }
        return sum;
    }
}
