// --------------------------------------------------------
// Code generated by GENAI
// --------------------------------------------------------

package catanllm;

/************************************************************/
/**
 * 
 */
import java.util.ArrayList;
import java.util.List;

public class Node {
    private final int nodeID;
    private final List<Node> neighbours = new ArrayList<>();
    private Building building;

    public Node(int nodeID) {
        this.nodeID = nodeID;
    }

    public int getNodeID() {
        return nodeID;
    }

    public boolean checkDice(int diceNum) {
        return false;
    }
}