// --------------------------------------------------------
// Code generated by GENAI
// --------------------------------------------------------

package catanllm;

/************************************************************/
/**
 * 
 */
public class PieceHandler {
	
	public void sendPiece(Piece piece) {}

    public void usePiece(Piece piece) {}
}
