// --------------------------------------------------------
// Code generated by GENAI
// --------------------------------------------------------

package catanllm;

/************************************************************/
/**
 * 
 */
public interface Piece {
    PlayerID ownerPlayerID();
    Player getOwnerPlayer(PlayerID id);
}