// --------------------------------------------------------
// Code generated by GENAI
// --------------------------------------------------------

package catanllm;

/************************************************************/
/**
 * 
 */
public interface PlayerHand extends Catalog {
	void addCard(Resource resource, int count);
    int count(Resource resource);
    boolean removeHand(Catalog catalog);
    boolean holdHand(Catalog catalog);
}
