// --------------------------------------------------------
// Code generated by GENAI
// --------------------------------------------------------

package catanllm;

/************************************************************/
/**
 * 
 */
import java.util.Random;

public class RegularDice implements Dice {
	 private final Random random = new Random();

	    @Override
	    public int roll() {
	        return random.nextInt(6) + 1;
	    }
}
