// --------------------------------------------------------
// Code generated by GENAI
// --------------------------------------------------------

package catanllm;

/************************************************************/
/**
 * 
 */
public class Road implements Piece {
    private final PlayerID owner;

    public Road(PlayerID owner) {
        this.owner = owner;
    }

    @Override
    public PlayerID ownerPlayerID() {
        return owner;
    }

    @Override
    public Player getOwnerPlayer(PlayerID id) {
        return null;
    }
}