// --------------------------------------------------------
// Code generated by GENAI
// --------------------------------------------------------

package catanllm;

/************************************************************/
/**
 * 
 */
public class Settlement extends Building {
    public Settlement(PlayerID owner) {
        super(owner);
    }
}