// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catanllm;

/************************************************************/
/**
 * 
 */
public interface StaticBoard {
	/**
	 * 
	 */
	public class board {
	};

	/**
	 * 
	 * @return 
	 */
	public PlayerID checkLongestRoad();

	/**
	 * 
	 * @param piece 
	 * @param node 
	 * @return 
	 */
	public boolean canPlace(Piece piece, Node node);
}
