// --------------------------------------------------------
// Code generated by GENAI
// --------------------------------------------------------

package catanllm;

/************************************************************/
/**
 * 
 */
public interface StaticBoard {
	boolean checkLongestRoad();
    boolean canPlace(Piece piece, Node node);
	
	/**
	 * 
	 * @return 
	 */
	public PlayerID checkLongestRoad();

	/**
	 * 
	 * @param piece 
	 * @param node 
	 * @return 
	 */
	public boolean canPlace(Piece piece, Node node);
}