// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catanllm;

/************************************************************/
/**
 * 
 */
public class Tile {
	/**
	 * 
	 */
	private Resource resource;
	/**
	 * 
	 */
	private int diceNum;
	/**
	 * 
	 */
	private int tileID;
	/**
	 * 
	 */
	public Catalog catalog;
}
