// --------------------------------------------------------
// Code generated by GENAI
// --------------------------------------------------------

package catanllm;

/************************************************************/
/**
 * 
 */
public class Tile {
    private final int tileID;
    private final Resource resource;
    private final int diceNum;

    public Tile(int tileID, Resource resource, int diceNum) {
        this.tileID = tileID;
        this.resource = resource;
        this.diceNum = diceNum;
    }
}